name: CI/CD
on:
    push:
        branches:
            - main
    pull_request:
        types: [synchronize]
    workflow_dispatch:
env:
    NODE_VERSION: 16.19.0
    FE_COMPONENT_LIBRARY: frontend/component-library
    FE_DASHBOARD: frontend/dashboard
    BASE_URL: ${{ secrets.BASE_URL }}
    BASE_PATH: ${{ secrets.BASE_PATH }}
    INTERNAL_COMPONENT_LIBRARY_URL: ${{ secrets.INTERNAL_COMPONENT_LIBRARY_URL }}
    USER_COMPONENT_LIBRARY_URL: ${{ secrets.USER_COMPONENT_LIBRARY_URL }}

jobs:
  deploy:
    name: Deploy Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ“¥ checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "ðŸ”  Verify Changed Files in ${{ env.FE_COMPONENT_LIBRARY }}"
        uses: tj-actions/changed-files@v35
        id: changed-component-library-files
        with:
            files: ${{ env.FE_COMPONENT_LIBRARY }}/**/*

      - name: "ðŸ”  Verify Changed Files in ${{ env.FE_DASHBOARD }}"
        uses: tj-actions/changed-files@v35
        id: changed-dashboard-files
        with:
            files: ${{ env.FE_DASHBOARD }}/**/*

      - name: "ðŸ”„  Cache node_modules"
        uses: actions/cache@v3
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: ${{ runner.os }}-node-
      
      - name: "ðŸ”§  Setup NodeJS ${{ env.NODE_VERSION }}"
        uses: actions/setup-node@v3
        with:
            node-version: ${{ env.NODE_VERSION }}

      - name: "ðŸ”§ Install npm@latest"
        run: npm i -g npm@latest  


      - name: "ðŸ“¦  Install Component Library Build dependencies"
        run: bash modulize.bash -e production -m component-library -p install 

      - name: "ðŸ—ï¸  Build Frontend Component Library"
        run: bash modulize.bash -e production -m component-library -p build

      - name: "ðŸšš  Package Component Library"
        run: |
          mkdir -p package/dist/component-library
          cp -r frontend/component-library/dist/* package/dist/component-library

      - name: "ðŸ“¦  Install Dashboard Build dependencies"
        run: bash modulize.bash -e production -m dashboard -p install

      - name: "ðŸ—ï¸  Build Frontend Dashboard"
        run: bash modulize.bash -e production -m dashboard -p build

      - name: "ðŸšš  Package Dashboard"
        run: |
          mkdir -p package/dist
          cp -r frontend/dashboard/out/* package/dist
          touch package/dist/.nojekyll
          touch package/dist/CNAME
          echo ${{ env.BASE_URL }} > package/dist/CNAME

      - name: "ðŸš€ Deploy to GitHub Pages"
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: package/dist
